name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
          
    - name: Nerdbank.GitVersioning
      uses: AArnott/nbgv@v0.3
    
    - run: echo 'NuGetPackageVersion ${{ steps.nbgv.outputs.NuGetPackageVersion }}'
