name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Nerdbank.GitVersioning
      uses: AArnott/nbgv@v0.3
    
    - run: echo 'SemVer2: ${{ steps.nbgv.outputs.NuGetPackageVersion }}'
